import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Grahas (Planets)',
      collapsed: true,
      items: [
        'grahas/index',
        {
          type: 'category',
          label: 'Individual Grahas',
          items: [
            'grahas/individual/index',
            'grahas/individual/sun',
            'grahas/individual/moon',
            'grahas/individual/mars',
            'grahas/individual/mercury',
            'grahas/individual/jupiter',
            'grahas/individual/venus',
            'grahas/individual/saturn',
            'grahas/individual/rahu',
            'grahas/individual/ketu',
          ],
        },
        {
          type: 'category',
          label: 'Planetary Concepts',
          items: [
            'grahas/concepts/index',
            'grahas/concepts/drishti',
            'grahas/concepts/digbal',
            'grahas/concepts/maran-karaka-sthan',
            'grahas/concepts/retrograde-combustion',
            'grahas/concepts/planetary-states',
            'grahas/concepts/maitreyi',
          ],
        },
        'grahas/general-notes',
      ],
    },
    {
      type: 'category',
      label: 'Rashis (Signs)',
      collapsed: true,
      items: [
        'rashis/index',
        'rashis/mesha',
        'rashis/vrishabha',
        'rashis/mithuna',
        'rashis/karka',
        'rashis/simha',
        'rashis/kanya',
        'rashis/tula',
        'rashis/vrishchika',
        'rashis/dhanu',
        'rashis/makara',
        'rashis/kumbha',
        'rashis/meena',
      ],
    },
    {
      type: 'category',
      label: 'Bhavas (Houses)',
      collapsed: true,
      items: [
        'bhavas/index',
        'bhavas/overview',
        'bhavas/first',
        'bhavas/second',
        'bhavas/third',
        'bhavas/fourth',
        'bhavas/fifth',
        'bhavas/sixth',
        'bhavas/seventh',
        'bhavas/eighth',
        'bhavas/ninth',
        'bhavas/tenth',
        'bhavas/eleventh',
        'bhavas/twelfth',
      ],
    },
    {
      type: 'category',
      label: 'Lagnas',
      collapsed: true,
      items: [
        'lagnas/index',
        'lagnas/mesha',
        'lagnas/vrishabha',
        'lagnas/mithuna',
        'lagnas/karka',
        'lagnas/simha',
        'lagnas/kanya',
        'lagnas/tula',
        'lagnas/vrishchika',
        'lagnas/dhanu',
        'lagnas/makara',
        'lagnas/kumbha',
        'lagnas/meena',
      ],
    },
    {
      type: 'category',
      label: 'Lords',
      collapsed: true,
      items: [
        'lords/index',
        'lords/1l',
        'lords/2l',
        'lords/3l',
        'lords/4l',
        'lords/5l',
        'lords/6l',
        'lords/7l',
        'lords/8l',
        'lords/9l',
        'lords/10l',
        'lords/11l',
        'lords/12l',
      ],
    },
    {
      type: 'category',
      label: 'Karakas',
      collapsed: true,
      items: [
        'karakas/index',
        'karakas/planetary-karakatva',
        'karakas/rashi-karakas',
      ],
    },
    'bhavat-bhavam',
    'panchada-maitreyi',
    {
      type: 'category',
      label: 'Nakshatras',
      collapsed: true,
      items: [
        'nakshatras/index',
        'nakshatras/find-my-nakshatra',
        'nakshatras/ashwini',
        'nakshatras/bharani',
        'nakshatras/krittika',
        'nakshatras/rohini',
        'nakshatras/mrigashira',
        'nakshatras/ardra',
        'nakshatras/punarvasu',
        'nakshatras/pushya',
        'nakshatras/ashlesha',
        'nakshatras/magha',
        'nakshatras/purva-phalguni',
        'nakshatras/uttara-phalguni',
        'nakshatras/hasta',
        'nakshatras/chitra',
        'nakshatras/swati',
        'nakshatras/vishakha',
        'nakshatras/anuradha',
        'nakshatras/jyeshtha',
        'nakshatras/mula',
        'nakshatras/purva-ashadha',
        'nakshatras/uttara-ashadha',
        'nakshatras/shravana',
        'nakshatras/dhanishtha',
        'nakshatras/shatabhisha',
        'nakshatras/purva-bhadrapada',
        'nakshatras/uttara-bhadrapada',
        'nakshatras/revati',
      ],
    },
    {
      type: 'category',
      label: 'Planets in Rashis',
      collapsed: true,
      items: [
        'planets-in-rashis/index',
        {
          type: 'category',
          label: '1. Sun in Rashis',
          items: [
            'planets-in-rashis/sun-in-rashis/index',
            'planets-in-rashis/sun-in-rashis/mesha',
            'planets-in-rashis/sun-in-rashis/vrishabha',
            'planets-in-rashis/sun-in-rashis/mithuna',
            'planets-in-rashis/sun-in-rashis/karka',
            'planets-in-rashis/sun-in-rashis/simha',
            'planets-in-rashis/sun-in-rashis/kanya',
            'planets-in-rashis/sun-in-rashis/tula',
            'planets-in-rashis/sun-in-rashis/vrishchika',
            'planets-in-rashis/sun-in-rashis/dhanu',
            'planets-in-rashis/sun-in-rashis/makara',
            'planets-in-rashis/sun-in-rashis/kumbha',
            'planets-in-rashis/sun-in-rashis/meena',
          ],
        },
        {
          type: 'category',
          label: '2. Moon in Rashis',
          items: [
            'planets-in-rashis/moon-in-rashis/index',
            'planets-in-rashis/moon-in-rashis/mesha',
            'planets-in-rashis/moon-in-rashis/vrishabha',
            'planets-in-rashis/moon-in-rashis/mithuna',
            'planets-in-rashis/moon-in-rashis/karka',
            'planets-in-rashis/moon-in-rashis/simha',
            'planets-in-rashis/moon-in-rashis/kanya',
            'planets-in-rashis/moon-in-rashis/tula',
            'planets-in-rashis/moon-in-rashis/vrishchika',
            'planets-in-rashis/moon-in-rashis/dhanu',
            'planets-in-rashis/moon-in-rashis/makara',
            'planets-in-rashis/moon-in-rashis/kumbha',
            'planets-in-rashis/moon-in-rashis/meena',
          ],
        },
        {
          type: 'category',
          label: '3. Mars in Rashis',
          items: [
            'planets-in-rashis/mars-in-rashis/index',
            'planets-in-rashis/mars-in-rashis/mesha',
            'planets-in-rashis/mars-in-rashis/vrishabha',
            'planets-in-rashis/mars-in-rashis/mithuna',
            'planets-in-rashis/mars-in-rashis/karka',
            'planets-in-rashis/mars-in-rashis/simha',
            'planets-in-rashis/mars-in-rashis/kanya',
            'planets-in-rashis/mars-in-rashis/tula',
            'planets-in-rashis/mars-in-rashis/vrishchika',
            'planets-in-rashis/mars-in-rashis/dhanu',
            'planets-in-rashis/mars-in-rashis/makara',
            'planets-in-rashis/mars-in-rashis/kumbha',
            'planets-in-rashis/mars-in-rashis/meena',
          ],
        },
        {
          type: 'category',
          label: '4. Mercury in Rashis',
          items: [
            'planets-in-rashis/mercury-in-rashis/index',
            'planets-in-rashis/mercury-in-rashis/mesha',
            'planets-in-rashis/mercury-in-rashis/vrishabha',
            'planets-in-rashis/mercury-in-rashis/mithuna',
            'planets-in-rashis/mercury-in-rashis/karka',
            'planets-in-rashis/mercury-in-rashis/simha',
            'planets-in-rashis/mercury-in-rashis/kanya',
            'planets-in-rashis/mercury-in-rashis/tula',
            'planets-in-rashis/mercury-in-rashis/vrishchika',
            'planets-in-rashis/mercury-in-rashis/dhanu',
            'planets-in-rashis/mercury-in-rashis/makara',
            'planets-in-rashis/mercury-in-rashis/kumbha',
            'planets-in-rashis/mercury-in-rashis/meena',
          ],
        },
        {
          type: 'category',
          label: '5. Jupiter in Rashis',
          items: [
            'planets-in-rashis/jupiter-in-rashis/index',
            'planets-in-rashis/jupiter-in-rashis/mesha',
            'planets-in-rashis/jupiter-in-rashis/vrishabha',
            'planets-in-rashis/jupiter-in-rashis/mithuna',
            'planets-in-rashis/jupiter-in-rashis/karka',
            'planets-in-rashis/jupiter-in-rashis/simha',
            'planets-in-rashis/jupiter-in-rashis/kanya',
            'planets-in-rashis/jupiter-in-rashis/tula',
            'planets-in-rashis/jupiter-in-rashis/vrishchika',
            'planets-in-rashis/jupiter-in-rashis/dhanu',
            'planets-in-rashis/jupiter-in-rashis/makara',
            'planets-in-rashis/jupiter-in-rashis/kumbha',
            'planets-in-rashis/jupiter-in-rashis/meena',
          ],
        },
        {
          type: 'category',
          label: '6. Venus in Rashis',
          items: [
            'planets-in-rashis/venus-in-rashis/index',
            'planets-in-rashis/venus-in-rashis/mesha',
            'planets-in-rashis/venus-in-rashis/vrishabha',
            'planets-in-rashis/venus-in-rashis/mithuna',
            'planets-in-rashis/venus-in-rashis/karka',
            'planets-in-rashis/venus-in-rashis/simha',
            'planets-in-rashis/venus-in-rashis/kanya',
            'planets-in-rashis/venus-in-rashis/tula',
            'planets-in-rashis/venus-in-rashis/vrishchika',
            'planets-in-rashis/venus-in-rashis/dhanu',
            'planets-in-rashis/venus-in-rashis/makara',
            'planets-in-rashis/venus-in-rashis/kumbha',
            'planets-in-rashis/venus-in-rashis/meena',
          ],
        },
        {
          type: 'category',
          label: '7. Saturn in Rashis',
          items: [
            'planets-in-rashis/saturn-in-rashis/index',
            'planets-in-rashis/saturn-in-rashis/mesha',
            'planets-in-rashis/saturn-in-rashis/vrishabha',
            'planets-in-rashis/saturn-in-rashis/mithuna',
            'planets-in-rashis/saturn-in-rashis/karka',
            'planets-in-rashis/saturn-in-rashis/simha',
            'planets-in-rashis/saturn-in-rashis/kanya',
            'planets-in-rashis/saturn-in-rashis/tula',
            'planets-in-rashis/saturn-in-rashis/vrishchika',
            'planets-in-rashis/saturn-in-rashis/dhanu',
            'planets-in-rashis/saturn-in-rashis/makara',
            'planets-in-rashis/saturn-in-rashis/kumbha',
            'planets-in-rashis/saturn-in-rashis/meena',
          ],
        },
        {
          type: 'category',
          label: '8. Rahu in Rashis',
          items: [
            'planets-in-rashis/rahu-in-rashis/index',
            'planets-in-rashis/rahu-in-rashis/mesha',
            'planets-in-rashis/rahu-in-rashis/vrishabha',
            'planets-in-rashis/rahu-in-rashis/mithuna',
            'planets-in-rashis/rahu-in-rashis/karka',
            'planets-in-rashis/rahu-in-rashis/simha',
            'planets-in-rashis/rahu-in-rashis/kanya',
            'planets-in-rashis/rahu-in-rashis/tula',
            'planets-in-rashis/rahu-in-rashis/vrishchika',
            'planets-in-rashis/rahu-in-rashis/dhanu',
            'planets-in-rashis/rahu-in-rashis/makara',
            'planets-in-rashis/rahu-in-rashis/kumbha',
            'planets-in-rashis/rahu-in-rashis/meena',
          ],
        },
        {
          type: 'category',
          label: '9. Ketu in Rashis',
          items: [
            'planets-in-rashis/ketu-in-rashis/index',
            'planets-in-rashis/ketu-in-rashis/mesha',
            'planets-in-rashis/ketu-in-rashis/vrishabha',
            'planets-in-rashis/ketu-in-rashis/mithuna',
            'planets-in-rashis/ketu-in-rashis/karka',
            'planets-in-rashis/ketu-in-rashis/simha',
            'planets-in-rashis/ketu-in-rashis/kanya',
            'planets-in-rashis/ketu-in-rashis/tula',
            'planets-in-rashis/ketu-in-rashis/vrishchika',
            'planets-in-rashis/ketu-in-rashis/dhanu',
            'planets-in-rashis/ketu-in-rashis/makara',
            'planets-in-rashis/ketu-in-rashis/kumbha',
            'planets-in-rashis/ketu-in-rashis/meena',
          ],
        },
      ],
    },
    'conjunctions',
    'degrees',
    'vakrattva',
    'rashi-drishti',
    {
      type: 'category',
      label: 'Yogas',
      collapsed: true,
      items: [
        'yogas/index',
        'yogas/overview',
        'yogas/raj-yoga',
        'yogas/dhan-yoga',
        'yogas/gaj-kesari-yoga',
        'yogas/unmaad-yoga',
      ],
    },
    {
      type: 'category',
      label: 'Dashas',
      collapsed: true,
      items: [
        'dashas/index',
        'dashas/reference',
        'dashas/case-study-saturn',
        {
          type: 'category',
          label: '1. सूर्य (Sun) Dasha',
          items: [
            'dashas/sun-dasha/index',
          ],
        },
        {
          type: 'category',
          label: '2. चंद्र (Moon) Dasha',
          items: [
            'dashas/moon-dasha/index',
          ],
        },
        {
          type: 'category',
          label: '3. मंगल (Mars) Dasha',
          items: [
            'dashas/mars-dasha/index',
          ],
        },
        {
          type: 'category',
          label: '4. बुध (Mercury) Dasha',
          items: [
            'dashas/mercury-dasha/index',
          ],
        },
        {
          type: 'category',
          label: '5. गुरु (Jupiter) Dasha',
          items: [
            'dashas/jupiter-dasha/index',
          ],
        },
        {
          type: 'category',
          label: '6. शुक्र (Venus) Dasha',
          items: [
            'dashas/venus-dasha/index',
          ],
        },
        {
          type: 'category',
          label: '7. शनि (Saturn) Dasha',
          items: [
            'dashas/saturn-dasha/index',
          ],
        },
        {
          type: 'category',
          label: '8. राहु (Rahu) Dasha',
          items: [
            'dashas/rahu-dasha/index',
          ],
        },
        {
          type: 'category',
          label: '9. केतु (Ketu) Dasha',
          items: [
            'dashas/ketu-dasha/index',
          ],
        },
        'dashas/notes',
      ],
    },
    'navmansha/index',
    'gochar',
    {
      type: 'category',
      label: 'BPHS',
      collapsed: true,
      items: [
        'BPHS/index',
        'BPHS/aristadhyayah',
        'BPHS/graha-names',
      ],
    },
    {
      type: 'category',
      label: 'Domain Specific',
      collapsed: true,
      items: [
        'domain-specific-astrology/index',
        {
          type: 'category',
          label: 'Professional Astrology',
          items: [
            'domain-specific-astrology/professional-astrology/index',
            'domain-specific-astrology/professional-astrology/astrologers',
            'domain-specific-astrology/professional-astrology/army',
            'domain-specific-astrology/professional-astrology/ca',
            'domain-specific-astrology/professional-astrology/chef',
            'domain-specific-astrology/professional-astrology/doctors',
            'domain-specific-astrology/professional-astrology/lawyer',
            'domain-specific-astrology/professional-astrology/mathematician',
            'domain-specific-astrology/professional-astrology/politicians',
            'domain-specific-astrology/professional-astrology/spirituality',
            'domain-specific-astrology/professional-astrology/insolvency',
          ],
        },
        {
          type: 'category',
          label: 'Medical Astrology',
          items: [
            'domain-specific-astrology/medical-astrology/index',
            'domain-specific-astrology/medical-astrology/depression',
          ],
        },
        'domain-specific-astrology/children-astrology/index',
        {
          type: 'category',
          label: 'Stock Market',
          items: [
            'domain-specific-astrology/stock-market-analysis/index',
            'domain-specific-astrology/stock-market-analysis/shani-industries',
            'domain-specific-astrology/stock-market-analysis/jupiter-market',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Mantras',
      collapsed: true,
      items: [
        'mantras/index',
        'mantras/gayatri-mantra',
        'mantras/mahamrityunjaya-mantra',
      ],
    },
    {
      type: 'category',
      label: 'Chanting',
      collapsed: true,
      items: [
        'chanting/index',
        'chanting/vishnu-sahasranam/index',
        'chanting/gayatri-mantra',
        'chanting/lalitha-sahasranam',
        'chanting/graha-beej-mantras',
      ],
    },
    {
      type: 'category',
      label: 'Research',
      collapsed: true,
      items: [
        'research/index',
      ],
    },
    {
      type: 'category',
      label: 'Talks',
      collapsed: true,
      items: [
        'talks/index',
        'talks/shani-moving-to-meen-29-mar-2025',
        'talks/ayurveda-and-astrology',
        'talks/sade-sati',
      ],
    },
    {
      type: 'category',
      label: 'Wiki',
      collapsed: true,
      items: [
        'wiki/index',
        'wiki/maharishi-parasara',
        'wiki/maharishi-patanjali',
        'wiki/hora-shastra',
        'wiki/yoga-sutras',
        'wiki/practical-remedies',
        {
          type: 'category',
          label: 'Avatars',
          items: [
            'wiki/avatars/index',
            'wiki/avatars/matsya',
            'wiki/avatars/kurma',
            'wiki/avatars/varaha',
            'wiki/avatars/narasimha',
            'wiki/avatars/vamana',
            'wiki/avatars/parashurama',
            'wiki/avatars/rama',
            'wiki/avatars/buddha',
            'wiki/avatars/krishna',
            'wiki/avatars/kalki',
          ],
        },
      ],
    },
    'vedic-chart',
  ],
};

export default sidebars;
