/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "📿 Vedic Astrology Notes",
  "tagline": "Comprehensive notes on Vedic Astrology",
  "favicon": "img/favicon.ico",
  "url": "https://astrology.viditaggarwal.com",
  "baseUrl": "/",
  "organizationName": "viditvia",
  "projectName": "nextjs_astrology_notes",
  "onBrokenLinks": "throw",
  "markdown": {
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    },
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "routeBasePath": "/",
          "sidebarPath": "./sidebars.ts",
          "include": [
            "**/*.mdx"
          ],
          "exclude": [
            "**/*.md",
            "**/Astrology/**"
          ],
          "sidebarCollapsed": true,
          "remarkPlugins": [
            [
              null,
              {}
            ]
          ],
          "rehypePlugins": [
            [
              null,
              {}
            ]
          ]
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    null,
    null
  ],
  "stylesheets": [
    {
      "href": "https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap",
      "type": "text/css"
    }
  ],
  "themeConfig": {
    "navbar": {
      "title": "📿 Vedic Astrology Notes",
      "items": [
        {
          "type": "doc",
          "docId": "index",
          "label": "Home",
          "position": "left"
        },
        {
          "type": "dropdown",
          "label": "Core",
          "position": "left",
          "items": [
            {
              "type": "doc",
              "docId": "grahas/index",
              "label": "Grahas (Planets)"
            },
            {
              "type": "doc",
              "docId": "rashis/index",
              "label": "Rashis (Signs)"
            },
            {
              "type": "doc",
              "docId": "bhavas/index",
              "label": "Bhavas (Houses)"
            },
            {
              "type": "doc",
              "docId": "nakshatras/index",
              "label": "Nakshatras"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Planets in Rashis",
          "position": "left",
          "items": [
            {
              "type": "doc",
              "docId": "planets-in-rashis/sun-in-rashis/index",
              "label": "Sun"
            },
            {
              "type": "doc",
              "docId": "planets-in-rashis/moon-in-rashis/index",
              "label": "Moon"
            },
            {
              "type": "doc",
              "docId": "planets-in-rashis/mars-in-rashis/index",
              "label": "Mars"
            },
            {
              "type": "doc",
              "docId": "planets-in-rashis/mercury-in-rashis/index",
              "label": "Mercury"
            },
            {
              "type": "doc",
              "docId": "planets-in-rashis/jupiter-in-rashis/index",
              "label": "Jupiter"
            },
            {
              "type": "doc",
              "docId": "planets-in-rashis/venus-in-rashis/index",
              "label": "Venus"
            },
            {
              "type": "doc",
              "docId": "planets-in-rashis/saturn-in-rashis/index",
              "label": "Saturn"
            },
            {
              "type": "doc",
              "docId": "planets-in-rashis/rahu-in-rashis/index",
              "label": "Rahu"
            },
            {
              "type": "doc",
              "docId": "planets-in-rashis/ketu-in-rashis/index",
              "label": "Ketu"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Nakshatras",
          "position": "left",
          "items": [
            {
              "type": "doc",
              "docId": "nakshatras/index",
              "label": "Overview"
            },
            {
              "type": "doc",
              "docId": "nakshatras/find-my-nakshatra",
              "label": "Find My Nakshatra"
            },
            {
              "type": "doc",
              "docId": "nakshatras/ashwini",
              "label": "Ashwini"
            },
            {
              "type": "doc",
              "docId": "nakshatras/bharani",
              "label": "Bharani"
            },
            {
              "type": "doc",
              "docId": "nakshatras/krittika",
              "label": "Krittika"
            },
            {
              "type": "doc",
              "docId": "nakshatras/rohini",
              "label": "Rohini"
            },
            {
              "type": "doc",
              "docId": "nakshatras/mrigashira",
              "label": "Mrigashira"
            },
            {
              "type": "doc",
              "docId": "nakshatras/ardra",
              "label": "Ardra"
            },
            {
              "type": "doc",
              "docId": "nakshatras/punarvasu",
              "label": "Punarvasu"
            },
            {
              "type": "doc",
              "docId": "nakshatras/pushya",
              "label": "Pushya"
            },
            {
              "type": "doc",
              "docId": "nakshatras/ashlesha",
              "label": "Ashlesha"
            },
            {
              "type": "doc",
              "docId": "nakshatras/magha",
              "label": "Magha"
            },
            {
              "type": "doc",
              "docId": "nakshatras/purva-phalguni",
              "label": "Purva Phalguni"
            },
            {
              "type": "doc",
              "docId": "nakshatras/uttara-phalguni",
              "label": "Uttara Phalguni"
            },
            {
              "type": "doc",
              "docId": "nakshatras/hasta",
              "label": "Hasta"
            },
            {
              "type": "doc",
              "docId": "nakshatras/chitra",
              "label": "Chitra"
            },
            {
              "type": "doc",
              "docId": "nakshatras/swati",
              "label": "Swati"
            },
            {
              "type": "doc",
              "docId": "nakshatras/vishakha",
              "label": "Vishakha"
            },
            {
              "type": "doc",
              "docId": "nakshatras/anuradha",
              "label": "Anuradha"
            },
            {
              "type": "doc",
              "docId": "nakshatras/jyeshtha",
              "label": "Jyeshtha"
            },
            {
              "type": "doc",
              "docId": "nakshatras/mula",
              "label": "Mula"
            },
            {
              "type": "doc",
              "docId": "nakshatras/purva-ashadha",
              "label": "Purva Ashadha"
            },
            {
              "type": "doc",
              "docId": "nakshatras/uttara-ashadha",
              "label": "Uttara Ashadha"
            },
            {
              "type": "doc",
              "docId": "nakshatras/shravana",
              "label": "Shravana"
            },
            {
              "type": "doc",
              "docId": "nakshatras/dhanishtha",
              "label": "Dhanishtha"
            },
            {
              "type": "doc",
              "docId": "nakshatras/shatabhisha",
              "label": "Shatabhisha"
            },
            {
              "type": "doc",
              "docId": "nakshatras/purva-bhadrapada",
              "label": "Purva Bhadrapada"
            },
            {
              "type": "doc",
              "docId": "nakshatras/uttara-bhadrapada",
              "label": "Uttara Bhadrapada"
            },
            {
              "type": "doc",
              "docId": "nakshatras/revati",
              "label": "Revati"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Analysis",
          "position": "left",
          "items": [
            {
              "type": "doc",
              "docId": "yogas/index",
              "label": "Yogas"
            },
            {
              "type": "doc",
              "docId": "dashas/index",
              "label": "Dashas"
            },
            {
              "type": "doc",
              "docId": "conjunctions",
              "label": "Conjunctions"
            },
            {
              "type": "doc",
              "docId": "domain-specific-astrology/index",
              "label": "Domain-Specific"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Reference",
          "position": "left",
          "items": [
            {
              "type": "doc",
              "docId": "wiki/index",
              "label": "Wiki"
            },
            {
              "type": "doc",
              "docId": "BPHS/index",
              "label": "BPHS"
            },
            {
              "type": "doc",
              "docId": "mantras/index",
              "label": "Mantras"
            },
            {
              "type": "doc",
              "docId": "chanting/index",
              "label": "Chanting"
            }
          ]
        },
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Browse All"
        },
        {
          "type": "html",
          "position": "right",
          "value": "<div id=\"auth-button-placeholder\"></div>"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "copyright": "Copyright © 2026 Vedic Astrology Documentation.",
      "links": []
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "dark",
      "respectPrefersColorScheme": true,
      "disableSwitch": false
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
